# This workflow is called in the 'tutorial--*' repositories to execute each
# Jupyter notebook and convert the output to .html and .pdf.
name: 'Execute and convert notebook'

inputs:
  python-version:
    type: string
    default: "3.12"
  tutorial-slug:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Enforce tutorial-slug input
      shell: bash
      run: |
        [[ "${{ inputs.tutorial-slug }}" ]] || { echo "inputs.tutorial-slug is empty" ; exit 1; }

    - name: Checkout
      uses: actions/checkout@v4
      with:
        clean: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Display Python version
      shell: bash
      run: python -c "import sys; print(sys.version)"
      
    # Execute and convert notebook
    - name: Install notebook and build requirements
      shell: bash
      run: | 
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        playwright install-deps
      
    - name: Use Jupyterbook to execute notebook, convert to HTML, generate pdf
      shell: bash
      run: | 
        jb build "${{ inputs.tutorial-slug }}".ipynb --config _config.yaml --builder pdfhtml
        cp -r "_build/_page/${{ inputs.tutorial-slug }}/html" html
        cp "_build/_page/${{ inputs.tutorial-slug }}/pdf/${{ inputs.tutorial-slug }}.pdf" html

    # - name: Upload converted notebook as an artifact
    #   uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: html_build
    #     path: html

    - name: Push converted notebook files to 'converted' branch
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@v4.6.4
      with:
        branch: converted
        folder: "html"
        single-commit: true
        clean: true
